default_platform :android

platform :android do
  desc "Build Android app for GitHub Release"
  lane :build_android_release do
    android_dir = File.expand_path('..', Dir.pwd)
    
    # Create google-services.json from GitHub secret
    File.write(
      File.join(android_dir, "app/google-services.json"),
      ENV["GOOGLE_SERVICES_JSON"]
    )
    
    # Build debug APK for GitHub Release (no signing required)
    gradle(
      task: "assembleDebug"
    )
  end
end
